# A base YAML configuration file for the custom nnUNet pretrained
# This is the same as ACSConv random
# Author: LouisDo2108
# Date: May 7, 2023

includes:
  - base.yaml

acsconv: True
nnUNet_init: True
acs_pretrained: resnet18
replace_all: False