# A base YAML configuration file for the custom nnUNet pretrained
# Variant: Original nnUNet
# Author: LouisDo2108
# Date: May 7, 2023

acsconv: False
acs_pretrained: resnet18
# (Currently only support HGGLGGClassifier, 
# since ImageNetBratsClassifier pretrained resnet18 encoder could be used with acs_pretrained instead
proxy_encoder_class: null # HGGLGGClassifier
proxy_encoder_pretrained: null # "/home/dtpthao/workspace/nnUNet/nnunetv2/tuanluc_dev/results/hgg_lgg/checkpoints/model_55.pt"
replace_all: False
nnUNet_init: True
jcs: False