# A base YAML configuration file for the custom nnUNet pretrained
# Variants: Replace nnUNet encoder with custom pretrained nnUNet encoder on classifiying HGG/LGG
# Author: LouisDo2108
# Date: May 7, 2023

includes:
  - acs_resnet18_encoder.yaml

# proxy_encoder_class: HGGLGGClassifier
# proxy_encoder_pretrained: "/home/dtpthao/workspace/nnUNet/nnunetv2/tuanluc_dev/results/hgg_lgg/checkpoints/model_55.pt"
# acsconv: True
# acs_pretrained: null
# nnUNet_init: True
jcs: True